### ISSUE TITLE
Find fix for zlib install.

### ISSUE THREAD

**Issue by Misly16** [ourcord/ourcord#4]
Solutions for this would be,
use https://github.com/nodeca/pako
or make our own

**Comment by matthewthechickenman** [comment]
Depends - _How hard could it be?_

**Comment by Misly16** [comment]
> 
> 
> Depends - _How hard could it be?_

haven't looked into it too much but from looking at eris and djs, neither of them use zlib

**Comment by matthewthechickenman** [comment]
> > Depends - _How hard could it be?_
> 
> haven't looked into it too much but from looking at eris and d.js, neither of them use zlib

Actually - d.js can use zlib (@discordjs/zlib) but that's just to speed things up. I would like to ship our own one with the module tho just to make it less of a pain in the arse to install.

**Comment by Misly16** [comment]
> 
> 
> > > Depends - _How hard could it be?_
> > 
> > 
> > haven't looked into it too much but from looking at eris and d.js, neither of them use zlib
> 
> Actually - d.js can use zlib (@discordjs/zlib) but that's just to speed things up. I would like to ship our own one with the module tho just to make it less of a pain in the arse to install.

yep, currently the only way to install it without some bs compiler is to use yarn

**Comment by matthewthechickenman** [comment]
This is done now, as far as I'm aware and according to [this](https://github.com/ourcord/ourcord/commit/592d5c3ba06654227159de67496de8d07bd8b30b).

**Comment by Misly16** [comment]
> 
> 
> This is done now, as far as I'm aware and according to [this](https://github.com/ourcord/ourcord/commit/592d5c3ba06654227159de67496de8d07bd8b30b).

As far as i'm aware, this will be a temp fix until we make our own solution.

**Comment by matthewthechickenman** [comment]
> > This is done now, as far as I'm aware and according to [this](https://github.com/ourcord/ourcord/commit/592d5c3ba06654227159de67496de8d07bd8b30b).
> 
> As far as I'm aware, this will be a temp fix until we make our own solution.

Or we could just keep it like that
