### ISSUE TITLE
Put documentation into proper repository

### ISSUE THREAD

**Issue by matthewthechickenman** [ourcord/ourcord#61]
Add the documentation to [this repo](https://github.com/ourcord/docs)

**Comment by alebot-dev** [comment]
i mean its not broken so why fix it

**Comment by matthewthechickenman** [comment]
> I mean it's not broken so why fix it
Why not keep it organised?

**Comment by alebot-dev** [comment]
@Misly16 handle this please im not a frontend person

**Comment by Misly16** [comment]
Too much effort, as you would have to build it and then transfer it all over

**Comment by matthewthechickenman** [comment]
> Too much effort, as you would have to build it and then transfer it all over

Why not build from that repo?

**Comment by Misly16** [comment]
Because you would need the source and npm installed with the dependencies

**Comment by matthewthechickenman** [comment]
> Because you would need the source and npm installed with the dependencies

Yeah, ok
