### ISSUE TITLE
[Urgent] <Client>.setStatus crashes the bot.

### ISSUE THREAD

**Issue by matthewthechickenman** [ourcord/ourcord#8]
It won't even give me an error, just crashes the bot. I'm doing everything according to the docs so I don't know what's going on.

**Comment by Misly16** [comment]
_Have you tried turning it off and on?_ Try looking at how eris does it and see if you're doing anything wrong or the docs are wrong

**Comment by matthewthechickenman** [comment]
Ahh, I'll try turning it off and on. Seriously, will do.

**Comment by alebot-dev** [comment]
I'll try looking at this asap. If catching does nothing then it means it closes the ws connection without attempting to retry

**Comment by matthewthechickenman** [comment]
> _Have you tried turning it off and on?_ Try looking at how eris does it and see if you're doing anything wrong or if the docs are wrong

I’m not seeing anything different about the way Eris handles it and we’re handling it right now, apart from a few added things.

**Comment by matthewthechickenman** [comment]
I've fixed it with the help of the all legendary Tim 😆
